# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: E:/vivado_projects/ODIN_272/ODIN_272.srcs/sources_1/bd/ODIN_design/ip/ODIN_design_processing_system7_0_0/ODIN_design_processing_system7_0_0.xci
# IP: The module: 'ODIN_design_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/vivado_projects/ODIN_272/ODIN_272.gen/sources_1/bd/ODIN_design/ip/ODIN_design_processing_system7_0_0/ODIN_design_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'ODIN_design_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: E:/vivado_projects/ODIN_272/ODIN_272.srcs/sources_1/bd/ODIN_design/ip/ODIN_design_processing_system7_0_0/ODIN_design_processing_system7_0_0.xci
# IP: The module: 'ODIN_design_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/vivado_projects/ODIN_272/ODIN_272.gen/sources_1/bd/ODIN_design/ip/ODIN_design_processing_system7_0_0/ODIN_design_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'ODIN_design_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
