# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/ODIN_EEC272/PYNQ-Z1_C.xdc

# Block Designs: bd/ODIN_design/ODIN_design.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ODIN_design || ORIG_REF_NAME==ODIN_design} -quiet] -quiet

# IP: bd/ODIN_design/ip/ODIN_design_processing_system7_0_0/ODIN_design_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ODIN_design_processing_system7_0_0 || ORIG_REF_NAME==ODIN_design_processing_system7_0_0} -quiet] -quiet

# IP: bd/ODIN_design/ip/ODIN_design_rst_ps7_0_100M_0/ODIN_design_rst_ps7_0_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ODIN_design_rst_ps7_0_100M_0 || ORIG_REF_NAME==ODIN_design_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/ODIN_design/ip/ODIN_design_axi_dma_0_0/ODIN_design_axi_dma_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ODIN_design_axi_dma_0_0 || ORIG_REF_NAME==ODIN_design_axi_dma_0_0} -quiet] -quiet

# IP: bd/ODIN_design/ip/ODIN_design_ODIN_0_0/ODIN_design_ODIN_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ODIN_design_ODIN_0_0 || ORIG_REF_NAME==ODIN_design_ODIN_0_0} -quiet] -quiet

# IP: bd/ODIN_design/ip/ODIN_design_AER_bus_0_0/ODIN_design_AER_bus_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ODIN_design_AER_bus_0_0 || ORIG_REF_NAME==ODIN_design_AER_bus_0_0} -quiet] -quiet

# IP: bd/ODIN_design/ip/ODIN_design_xbar_1/ODIN_design_xbar_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ODIN_design_xbar_1 || ORIG_REF_NAME==ODIN_design_xbar_1} -quiet] -quiet

# IP: bd/ODIN_design/ip/ODIN_design_axi_mem_intercon_0/ODIN_design_axi_mem_intercon_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ODIN_design_axi_mem_intercon_0 || ORIG_REF_NAME==ODIN_design_axi_mem_intercon_0} -quiet] -quiet

# IP: bd/ODIN_design/ip/ODIN_design_ps7_0_axi_periph_0/ODIN_design_ps7_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ODIN_design_ps7_0_axi_periph_0 || ORIG_REF_NAME==ODIN_design_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/ODIN_design/ip/ODIN_design_xbar_2/ODIN_design_xbar_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ODIN_design_xbar_2 || ORIG_REF_NAME==ODIN_design_xbar_2} -quiet] -quiet

# IP: bd/ODIN_design/ip/ODIN_design_AXI_SPI_LOADER_0_0/ODIN_design_AXI_SPI_LOADER_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ODIN_design_AXI_SPI_LOADER_0_0 || ORIG_REF_NAME==ODIN_design_AXI_SPI_LOADER_0_0} -quiet] -quiet

# IP: bd/ODIN_design/ip/ODIN_design_SPI_Master_0_0/ODIN_design_SPI_Master_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ODIN_design_SPI_Master_0_0 || ORIG_REF_NAME==ODIN_design_SPI_Master_0_0} -quiet] -quiet

# IP: bd/ODIN_design/ip/ODIN_design_system_ila_0_0/ODIN_design_system_ila_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ODIN_design_system_ila_0_0 || ORIG_REF_NAME==ODIN_design_system_ila_0_0} -quiet] -quiet

# IP: bd/ODIN_design/ip/ODIN_design_auto_us_0/ODIN_design_auto_us_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ODIN_design_auto_us_0 || ORIG_REF_NAME==ODIN_design_auto_us_0} -quiet] -quiet

# IP: bd/ODIN_design/ip/ODIN_design_auto_us_1/ODIN_design_auto_us_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ODIN_design_auto_us_1 || ORIG_REF_NAME==ODIN_design_auto_us_1} -quiet] -quiet

# IP: bd/ODIN_design/ip/ODIN_design_auto_pc_0/ODIN_design_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ODIN_design_auto_pc_0 || ORIG_REF_NAME==ODIN_design_auto_pc_0} -quiet] -quiet

# IP: bd/ODIN_design/ip/ODIN_design_auto_pc_1/ODIN_design_auto_pc_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ODIN_design_auto_pc_1 || ORIG_REF_NAME==ODIN_design_auto_pc_1} -quiet] -quiet

# XDC: e:/vivado_projects/ODIN_272/ODIN_272.gen/sources_1/bd/ODIN_design/ODIN_design_ooc.xdc
